# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

jobs:
  include:
    - r: bioc-release
    - r: release
      script: Rscript -e 'remotes::install_cran("BiocManager"); BiocManager::install(c("llrs/BaseSet", dependencies = TRUE)'
after_success:
    - Rscript -e 'covr::codecov()'

notifications: # To avoid filling the inbox
  email:
    on_success: change
    on_failure: change

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
